### ISSUE TITLE
您好，有办法正确识别视频的时长和帧数吗？

### ISSUE THREAD

**Issue by zhaowtVincent** [IuvenisSapiens/ComfyUI_MiniCPM-V-2_6-int4#2]
![image](https://github.com/user-attachments/assets/47931a6b-64a5-4e4c-8088-da9d16b19fdb)
这个视频实际有六秒，帧数是6秒*30帧=180帧

**Comment by IuvenisSapiens** [comment]
这个问题无法直接回答，这是因为模型分析视频内容的策略本质上是根据帧率抽取部分帧画面，从抽取到的静态帧画面中进行推理，从而给出答案。
