### ISSUE TITLE
Please add `Seed` and `Unload model after generation` options.

### ISSUE THREAD

**Issue by 925-Studio** [IuvenisSapiens/ComfyUI_MiniCPM-V-2_6-int4#5]
First, thanks for your work. Your node works great. But maybe you can consider add those feature like I mentioned in the title. `Seed` will give more control and `Unload model after generation` will be a great help with the `OOM` problem.

**Comment by IuvenisSapiens** [comment]
- `seed` parameter has been added.
- `Offload model to CPU` is not supported for `4-bit` or `8-bit` bitsandbytes models.
